[package]
name = "saw_raycaster"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3
debug = false

[dependencies]
minifb = "0.26"
nalgebra-glm = "0.18"
rodio = "0.21"
image = { version = "0.25", default-features = false, features = ["png"] }
winapi = { version = "0.3", features = ["winuser"] }
